# sudo
sudo: false

# Could install itk to speed up build but 
#  travis does not seem to like it...
#sudo: required
#before_script:
#  - sudo apt-get install libinsighttoolkit4-dev
#script: 
#  - cmake -DUSE_SYSTEM_ITK:BOOL=ON ../semex

language: cpp

compiler:
  - gcc

before_script:
  - cmake --version

script: 
  - cd ..
  - mkdir build
  - cd build
  - cmake ../semex
  - make
  - cd TheLib-build
  
