# not using sudo
sudo: false

language: cpp

compiler:
  - gcc

# install itk to speed up build
before_script:
  - cmake --version
  - apt-get install libinsighttoolkit4-dev

script: 
  - cd ..
  - mkdir build
  - cd build
  - cmake -DUSE_SYSTEM_ITK:BOOL=ON ../semex
  - make
  - cd TheLib-build
  
